### ISSUE TITLE
Is there a way to specify default tax rate for everything?

### ISSUE THREAD

**Issue by ghost** [SolarNetwork/killbill-easytax-plugin#3]
I'd put this question in a forum if I could find one.
I have two issues: 

- external charges seem to match every tax rate so I get multiple tax entries on an external charge invoice.
- I would really like to have one default tax rate for all products (and external charges) and then add more specific rates for specific products. I don't see how to configure this.

Thanks for any help

**Comment by msqr** [comment]
I'm sorry to say we at SolarNetwork are no longer using Kill Bill and thus not working on this project any more. Your first point sounds like it's probably a bug; your second point sounds like a nice feature request. Maybe there's another user out there that would be interested in helping you with those. 🤞
